name: Build/release

on:
  push:
    tags:
    - '*'    

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 21.1.0

      - name: Install Dependencies
        run: npm install
    
      - name: Publish
        run: npm run publish

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: dpwallet
          path: |
                ${{ github.workspace }}/out/make/squirrel.windows/x64/*.exe
  
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "out/make/squirrel.windows/x64/*.exe"
